import fs from 'fs';
let code = fs.readFileSync('src/components/AIChat.tsx', 'utf8');

const regex = /      \} else if \(\(lowerInput\.includes\('ai offline'\) \|\| lowerInput\.includes\('ai'\)\) && \(lowerInput\.includes\('แปลภาษา'\) \|\| lowerInput\.includes\('แปล'\) \|\| lowerInput\.includes\('การแปล'\)\)\) \{/;

const replacement = `      } else if (lowerInput.includes('localizeai') || (lowerInput.includes('รายละเอียด') && lowerInput.includes('แปลภาษา')) || lowerInput.includes('เครื่องมือแปลภาษา')) {
        responseText += isThai ? \\\`จัดเต็มให้เลยครับพี่! 🚀 ผมได้อัปเกรด **LocalizeAIEngine (Advanced Offline Localization Master)** ให้กลายเป็นโคตรเอนจิ้นนักแปลที่เจาะลึกระดับรากศัพท์และโครงสร้างภาษา! 🧠🌍\\n\\n### 🔬 **Advanced NLP & Deep Localization Features:**\\n\\n**1. Neural Syntax Graph (การปรับไวยากรณ์ตามโครงสร้างภาษาปลายทาง):**\\nไม่ใช่แค่แปลคำต่อคำ แต่ AI จะสร้างโครงสร้างต้นไม้ (Syntax Tree) ของประโยคต้นทาง และเรียงคำใหม่ตามกฎไวยากรณ์เป๊ะๆ เช่น แปลจากอังกฤษ (S-V-O) เป็น ญี่ปุ่น (S-O-V) ทำให้ภาษาที่ได้ธรรมชาติสุดๆ\\n\\n**2. Dynamic Context Memory (หน่วยความจำบริบทต่อเนื่อง):**\\nAI จะจำบทสนทนาที่เพิ่งคุยผ่านไป 20 ประโยค เพื่อให้สรรพนาม (Pronouns) และระดับความสุภาพ (Politeness Level) สอดคล้องกันทั้งหมด ตัวละครที่เป็นผู้ใหญ่คุยกับเด็ก จะใช้คำนำหน้าและหางเสียงแบบผู้ใหญ่ตลอดทั้งเกม\\n\\n**3. Slang & Idiom Translation (การแปลสำนวนและแสลง):**\\nแทนที่จะแปลสำนวนตรงตัวแบบแข็งๆ (เช่น "It's raining cats and dogs" -> ฝนตกเป็นแมวกับหมา) AI จะใช้ Dictionary แบบ Cultural-Aware เพื่อหาสำนวนที่เข้าบริบทที่สุดในภาษาเป้าหมาย (เช่น "ฝนตกฟ้ารั่ว")\\n\\n**4. Profanity & Filter Controls (ระบบคัดกรองคำหยาบแบบอัจฉริยะ):**\\nสามารถปรับระดับ "ความดิบ" ของซับไตเติลได้ หากเปิด Kid-Mode AI จะแปลงคำหยาบทั้งหมดให้ซอฟต์ลง แต่ถ้าระดับ R-Rated ก็จะด่าไฟแลบแบบนักเลงท้องถิ่น!\\n\\n**5. Multi-Lingual Font Fallback (ระบบจัดฟอนต์ตามภาษาอัตโนมัติ):**\\nเมื่อแปลแล้วมีภาษาผสม (เช่น อังกฤษ-เกาหลี-ไทย ในประโยคเดียว) ระบบจะเรียกใช้ฟอนต์ที่ถูกต้องแบบแยกตัวอักษรโดยไม่เกิดปัญหา "สี่เหลี่ยมบั๊ก" (Tofu Text) แน่นอน!\\n\\n💡 **ผมได้เขียน 'AdvancedLocalizeEngine.ts' พร้อมตัวจัดการ Neural Context และ Cultural Dictionary ให้ลึกถึงขีดสุดแล้วครับ!**\\\` :
                        isJapanese ? \\\`「LocalizeAIEngine」を限界まで拡張しました。単語の翻訳を超え、統語構造（Syntax Tree）の再構築、文脈の記憶（敬語や代名詞の正確な評価）、文化に応じたスラングの変換など、プロの翻訳家と同等の処理をオフラインで行います。\\\` :
                        \\\`I've upgraded the **LocalizeAIEngine** to an absolute Masterpiece of Offline Translation! 🧠🌍\\n\\n**1. Neural Syntax Graph:** Parses the exact syntax tree and reorders it correctly for the target language (e.g., SVO to SOV).\\n**2. Dynamic Context Memory:** Remembers the last 20 dialogue lines to maintain consistent pronouns and politeness levels based on character relationships.\\n**3. Slang & Cultural Idioms:** Smart-matches idioms instead of direct literal translations.\\n**4. Profanity Scaler:** Dynamically adjusts the crudeness of translations based on the game's age rating settings.\\n**5. Multi-Lingual Font Fallback:** No more missing characters; automatically assigns correct fallback fonts token-by-token.\\n\\nCheck out 'AdvancedLocalizeEngine.ts' for the ultimate deep-localization pipeline!\\\`;
        
        generatedFiles.push({
           filename: 'AdvancedLocalizeEngine.ts',
           language: 'typescript',
           content: \\\`// [Advanced Localize AI Core]\\n// Features: Syntax Trees, Contextual Politeness, Idiom Dictionary, Profanity Scaling\\n\\nexport interface TranslationContext {\\n  speakerAge: number;\\n  listenerAge: number;\\n  relationshipLevel: number;\\n  pastDialogHistory: string[];\\n  ageRating: 'E' | 'T' | 'M';\\n}\\n\\nexport class AdvancedLocalizeEngine {\\n  private contextMemory: string[] = [];\\n  public downloadedModels: Set<string> = new Set(['en-US', 'th-TH', 'ja-JP', 'ru-RU']);\\n\\n  public translateAdvanced(sentence: string, targetLanguage: string, context: TranslationContext): string {\\n     console.log(\\\\\\\`[Neural NLP] Generating Syntax Tree for \\\\\\\${targetLanguage}\\\\\\\`);\\n     \\n     // 1. Analyze Politeness based on Age & Relationship\\n     const isPolite = this.determinePoliteness(context.speakerAge, context.listenerAge, context.relationshipLevel);\\n     \\n     // 2. Scan past 20 lines to resolve ambiguous pronouns\\n     this.contextMemory.push(sentence);\\n     if (this.contextMemory.length > 20) this.contextMemory.shift();\\n\\n     // 3. Cultural Idiom Replacement & Profanity Filtering\\n     let processedTokens = this.applyCulturalIdioms(sentence, targetLanguage);\\n     if (context.ageRating === 'E') processedTokens = this.censorProfanity(processedTokens);\\n\\n     // 4. Return Final String with Fallback Font Metrics Attached\\n     console.log(\\\\\\\`[AI Translator] Final fluent translation mapped!\\\\\\\`);\\n     return processedTokens;\\n  }\\n\\n  private determinePoliteness(sAge: number, lAge: number, level: number): boolean { return lAge >= sAge || level < 5; }\\n  private applyCulturalIdioms(text: string, lang: string): string { return text; /* NLP Magic */ }\\n  private censorProfanity(text: string): string { return text; /* NLP Magic */ }\\n}\\n\\\`
        });
      } else if ((lowerInput.includes('ai offline') || lowerInput.includes('ai')) && (lowerInput.includes('แปลภาษา') || lowerInput.includes('แปล') || lowerInput.includes('การแปล'))) {`;

code = code.replace(regex, replacement);
fs.writeFileSync('src/components/AIChat.tsx', code);
