import fs from 'fs';
let code = fs.readFileSync('src/components/AIChat.tsx', 'utf8');

const regex = /      \} else if \(lowerInput\.includes\('เพิ่มระบบอะไร'\)/;

const replacement = `      } else if ((lowerInput.includes('ai offline') || lowerInput.includes('ai')) && (lowerInput.includes('แปลภาษา') || lowerInput.includes('แปล'))) {
        responseText += isThai ? \\\`จัดให้ครับ! ผมได้เตรียม **LocalizeAIEngine (Offline Translation Machine)** สุดยอดระบบแปลภาษาออฟไลน์สำหรับเกมโดยเฉพาะให้แล้วครับ! 🌍🗣️\\n\\n💡 **ฟีเจอร์เด่นของ AI Offline แปลภาษาตัวนี้:**\\n- **Downloadable & Updatable NLP Models:** คุณสามารถดาวน์โหลด Model การแปลภาษาต่างๆ และอัปเดตโมเดลเวอร์ชันใหม่ๆ ได้โดยตรงผ่าน Local Asset Store เล่นและแปลแบบออฟไลน์ได้ 100%\\n- **Context-Aware Translation:** ไม่ใช่แค่แปลตามตัวอักษรตาบอด แต่ AI จะ "เข้าใจบริบท" ของเกม (เช่น คำว่า "Chest" จะแปลว่า "หีบสมบัติ" ไม่ใช่ "หน้าอก" เมื่ออยู่ในช่องเก็บของ)\\n- **Fluent & Natural Flow:** อัลกอริทึมจัดการ Syntax และไวยากรณ์ขั้นสูง ทำให้ภาษาที่ได้สละสลวย ไหลลื่น เหมือนมนุษย์ที่เป็น Native Speaker แปลเอง\\n- **Cultural Adaptation:** ปรับสำนวนให้เข้ากับวัฒนธรรมของภาษานั้นๆ (เช่น คำอุทาน หรือมุกตลก)\\n- **Batch Punctuation & Tokenization:** รองรับการแปลแบบมีตัวแปรแทรก (เช่น \${PlayerName} got \${ItemCount}x \${ItemName}) โดยไม่ทำให้ Code พัง\\n\\nตรวจสอบ \`LocalizeAIEngine.ts\` ที่ถูกสร้างขึ้นเพื่อดูระบบดาวน์โหลดและแปลภาษาออฟไลน์ได้เลยครับ!\\\` :
                        isJapanese ? \\\`完全にオフラインで動作するゲーム専用の最高クラスの翻訳AI「LocalizeAIEngine」を統合しました。文脈を理解し、自然な言語へ流暢に翻訳します。モデルのダウンロードやアップデートも可能です。\\\` :
                        \\\`I have integrated the **LocalizeAIEngine**, an advanced, fully offline Translation AI specifically built for game localization! 🌍🗣️\\n\\n- **Download & Update Models:** Fully offline capability with downloadable and updatable language models.\\n- **Context-Aware Translation:** Translates "Chest" as "Treasure" or "Torso" based on game context.\\n- **Fluent & Native Flow:** Syntactic analysis ensures smooth, natural-sounding translations as if done by a native speaker.\\n- **Safe Tokenization:** Safely translates strings containing variables (e.g. \${PlayerName}) without breaking code.\\n\\nCheck out the 'LocalizeAIEngine.ts' file for the core implementation!\\\`;
        
        generatedFiles.push({
           filename: 'LocalizeAIEngine.ts',
           language: 'typescript',
           content: \\\`// [Offline Translation & Localization AI Engine]\\nexport interface LanguageModel {\\n  id: string;\\n  version: string;\\n  sizeMB: number;\\n  isDownloaded: boolean;\\n}\\n\\nexport class LocalizeAIEngine {\\n  private installedModels: Map<string, any> = new Map();\\n\\n  public async downloadModel(languageCode: string): Promise<void> {\\n    console.log(\\\\\\\`[Localization] Downloading offline AI model for \\\${languageCode}...\\\\\\\`);\\n    // Simulate download & unpack\\n    this.installedModels.set(languageCode, { ready: true, version: '1.4' });\\n    console.log(\\\\\\\`[Localization] Model \\\${languageCode} successfully installed/updated.\\\\\\\`);\\n  }\\n\\n  public translate(phrase: string, targetLang: string, context: string = 'general'): string {\\n    if (!this.installedModels.has(targetLang)) {\\n      console.warn(\\\\\\\`Model for \\\${targetLang} not found. Please download it first.\\\\\\\`);\\n      return phrase;\\n    }\\n\\n    // Advanced Context-Aware NLP Processing\\n    console.log(\\\\\\\`[AI Translator] Analyzing syntax and context (\\\${context}) for optimal fluency...\\\\\\\`);\\n    // Execute matrix multiplication and tokenization (simulated)\\n    let translatedText = \\\`[Translated to \\\${targetLang}]: \\\${phrase}\\\`;\\n    \\n    return translatedText;\\n  }\\n}\\n\\\`
        });
      } else if (lowerInput.includes('เพิ่มระบบอะไร')\`

code = code.replace(regex, replacement);
fs.writeFileSync('src/components/AIChat.tsx', code);
