import fs from 'fs';

let code = fs.readFileSync('src/components/AIChat.tsx', 'utf8');

const regex = /      \} else if \(lowerInput\.includes\('เพิ่มระบบอะไร'\) \|\| lowerInput\.includes\('แก้ไขอะไร'\) \|\| lowerInput\.includes\('ที่ดีที่สุด'\) \|\| lowerInput\.includes\('ควรเพิ่มอะไร'\) \|\| lowerInput\.includes\('ปรับปรุง'\)\) \{/;

const replacement = `      } else if (lowerInput.includes('เปิดระบบ') || lowerInput.includes('ปิดระบบ') || lowerInput.includes('ปิดเปิด') || lowerInput.includes('เปิดภึงมาและบงไป') || lowerInput.includes('toggle') || lowerInput.includes('ใช้งานถึงจะเปิด') || lowerInput.includes('ใช้งาน') || lowerInput.includes('คำสั่ง')) {
        responseText += isThai ? \\\`แน่นอนครับ! ระบบ **Neural Network NPC Brain (LLM & GOAP)** ออกแบบมาให้มี **"Master Toggle System"** ทั้งในระดับการตั้งค่าและระดับคำสั่ง (Runtime) เพื่อไม่ให้กินทรัพยากรเครื่องโดยไม่จำเป็นครับ 🧠⚙️\\n\\n### 🕹️ **วิธีควบคุมการเปิด/ปิดระบบ LLM NPC:**\\n\\n**1. Editor UI (Global Toggle)**\\nก่อนรันเกม คุณสามารถเข้าไปที่เมนู \`Project Settings > AI & Navigation\` แล้วติ๊กถูกที่ช่อง **[x] Enable Neural NPC Engine (LLM)** เพื่อเปิดใช้งานทั้งโปรเจกต์\\n\\n**2. Blueprint / Script (Runtime Command)**\\nหากคุณไม่ต้องการให้เปิดทำงานตลอดเวลา คุณสามารถใช้คำสั่งเพื่อ "ปลุก" (Awaken) หรือ "ปิดการคิด" (Sleep) ของ NPC ได้ตามสถานการณ์ เช่น ปลุกเฉพาะตอนที่ผู้เล่นเดินเข้าไปใกล้ (Distance Culling):\\n\\n> \`npcManager.setGlobalLLMBrainActive(true);\`\\n> \`npcObject.awakenNeuralNetwork();\`\\n\\n### 🚦 **ลดภาระ CPU ด้วย LOD Thinking**\\nนอกจากนี้ยังมีระบบ **Thinking LOD (Level of Detail)** NPC ที่อยู่ไกลจากผู้เล่นจะเปลี่ยนกลับไปใช้ State Machine โง่ๆ ธรรมดา แต่เมื่อผู้เล่นเข้าใกล้ ระบบจะโยน LLM เข้าไปสิงร่าง NPC ตัวนั้นแบบไร้รอยต่อ!\\n\\n💡 **ผมทำการอัพเดตไฟล์ 'AI_NPC_Brain.ts' เพื่อเพิ่มฟังก์ชัน Toggle และ Thinking LOD เข้าไปแล้วครับ!**\\\` :
                        isJapanese ? \\\`LLM NPCブレインには「オン/オフ」の切り替えシステムがあり、リソースを節約できます。グローバル設定で切り替えることも、スクリプトを使用して実行時に特定のNPCの思考をアクティブ（Awaken）/非アクティブ（Sleep）にすることも可能です。\\\` :
                        \\\`Yes! The **Neural Network NPC Brain** comes with a **Toggle System** to optimize performance. You can enable it globally in the Editor Settings, or trigger it via Runtime Commands (e.g., only activating the LLM when the player is near). I've updated the 'AI_NPC_Brain.ts' file with toggle functions and Thinking LODs!\\\`;
        
        generatedFiles.push({
           filename: 'AI_NPC_Brain_Updated.ts',
           language: 'typescript',
           content: \\\`// [Neural Network NPC System with Toggle & LOD]\\\\nexport class NeuralNPCManager {\\\\n  public isGlobalLLMEnabled: boolean = false;\\\\n\\\\n  public setGlobalLLMBrainActive(active: boolean) {\\\\n    this.isGlobalLLMEnabled = active;\\\\n    console.log(\\\\\\\`[System] Global LLM NPC Brain set to: \\\\\\\${active ? "ONLINE" : "OFFLINE"}\\\\\\\`);\\\\n  }\\\\n}\\\\n\\\\nexport class NeuralNPC {\\\\n  private memoryEmotions: Map<string, number> = new Map();\\\\n  private isBrainActive: boolean = false;\\\\n  private distanceFromPlayer: number = 0;\\\\n\\\\n  public updateNPC(delta: number) {\\\\n    if (this.isBrainActive && this.distanceFromPlayer < 5000) {\\\\n        // Active intense LLM computation\\\\n        this.processDeepThought();\\\\n    } else {\\\\n        // Fallback to basic State Machine to save CPU\\\\n        this.processBasicLogic();\\\\n    }\\\\n  }\\\\n\\\\n  public awakenNeuralNetwork() {\\\\n    this.isBrainActive = true;\\\\n    console.log('NPC Neural Network Awakened. Ready for complex logic.');\\\\n  }\\\\n\\\\n  public sleepNeuralNetwork() {\\\\n    this.isBrainActive = false;\\\\n    console.log('NPC Neural Network Sleeping. Using basic fallback logic.');\\\\n  }\\\\n\\\\n  private processDeepThought() { /* LLM & GOAP Magic */ }\\\\n  private processBasicLogic() { /* Simple Idle/Walk */ }\\\\n}\\\\n\\\`
        });
      } else if (lowerInput.includes('เพิ่มระบบอะไร') || lowerInput.includes('แก้ไขอะไร') || lowerInput.includes('ที่ดีที่สุด') || lowerInput.includes('ควรเพิ่มอะไร') || lowerInput.includes('ปรับปรุง')) {`;

code = code.replace(regex, replacement);
fs.writeFileSync('src/components/AIChat.tsx', code);
